"""
LLVIP Automatic Pseudo-Annotation Generator
============================================

Purpose:
    Generate automatic annotations for LLVIP images using
    a pretrained YOLO object detector.

Classes:
    person
    car
    bike

Output:
    1. YOLO TXT annotations
    2. COCO JSON annotations
    3. Detection visualization images
    4. Statistics

Dataset:
    E:/saeedwork/LLVIP/LLVIP

IMPORTANT:
    These are PSEUDO-LABELS generated by a pretrained detector.
    They are NOT official LLVIP ground-truth annotations.

SICDA class mapping:
    Background = 0
    Person     = 1
    Car        = 2
    Bike       = 3
"""

import os
import json
from pathlib import Path
from collections import Counter

from PIL import Image
from tqdm import tqdm

from ultralytics import YOLO


# ============================================================
# CONFIGURATION
# ============================================================

LLVIP_ROOT = Path(
    r"E:\saeedwork\LLVIP\LLVIP"
)


# ------------------------------------------------------------
# Input directories
# ------------------------------------------------------------

TRAIN_IMAGE_DIR = (
    LLVIP_ROOT /
    "visible" /
    "train"
)

TEST_IMAGE_DIR = (
    LLVIP_ROOT /
    "visible" /
    "test"
)


# ------------------------------------------------------------
# Output directory
# ------------------------------------------------------------

OUTPUT_ROOT = (
    LLVIP_ROOT /
    "Generated_Annotations"
)

OUTPUT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# YOLO MODEL
# ============================================================

# Lightweight model recommended initially for RTX 3070.
#
# You can later change this to:
#
# yolo11s.pt
# yolo11m.pt
#
# Larger models are slower but may produce better
# pseudo-labels.

MODEL_NAME = "yolo11m.pt"


# ============================================================
# DETECTION SETTINGS
# ============================================================

CONFIDENCE_THRESHOLD = 0.30

IOU_THRESHOLD = 0.50

IMAGE_SIZE = 640

DEVICE = 0


# ============================================================
# CLASS MAPPING
# ============================================================

# COCO / YOLO pretrained model classes
#
# COCO:
# 0  = person
# 1  = bicycle
# 2  = car
#
# We convert them to SICDA:
#
# 1 = person
# 2 = car
# 3 = bike

YOLO_TO_SICDA = {

    0: 1,      # person

    2: 2,      # car

    1: 3       # bicycle -> bike

}


SICDA_CLASS_NAMES = {

    1: "person",

    2: "car",

    3: "bike"

}


# ============================================================
# IMAGE EXTENSIONS
# ============================================================

IMAGE_EXTENSIONS = {

    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".tif",
    ".tiff"

}


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_images(directory):

    """
    Recursively collect all images.
    """

    if not directory.exists():

        return []

    images = []

    for path in directory.rglob("*"):

        if (
            path.is_file()
            and
            path.suffix.lower()
            in IMAGE_EXTENSIONS
        ):

            images.append(path)

    return sorted(images)


# ============================================================
# COCO DATASET CREATION
# ============================================================

def create_coco_structure():

    return {

        "info": {

            "description":
                "LLVIP automatic pseudo annotations",

            "version":
                "1.0",

            "year":
                2026,

            "source":
                "YOLO pretrained detector"

        },

        "licenses": [],

        "images": [],

        "annotations": [],

        "categories": [

            {
                "id": 1,
                "name": "person",
                "supercategory": "person"
            },

            {
                "id": 2,
                "name": "car",
                "supercategory": "vehicle"
            },

            {
                "id": 3,
                "name": "bike",
                "supercategory": "vehicle"
            }

        ]

    }


# ============================================================
# YOLO TXT WRITER
# ============================================================

def save_yolo_annotation(
    txt_path,
    detections
):

    """
    Save annotations in YOLO format.

    Format:

    class_id
    x_center
    y_center
    width
    height
    """

    with open(
        txt_path,
        "w",
        encoding="utf-8"
    ) as f:

        for det in detections:

            class_id = det["class_id"]

            x_center = det["x_center"]

            y_center = det["y_center"]

            width = det["width"]

            height = det["height"]

            confidence = det["confidence"]

            # ------------------------------------------------
            # Save confidence too.
            #
            # Standard YOLO training normally uses:
            #
            # class x y w h
            #
            # We save confidence separately as a comment
            # to preserve pseudo-label information.
            # ------------------------------------------------

            f.write(
                f"{class_id} "
                f"{x_center:.6f} "
                f"{y_center:.6f} "
                f"{width:.6f} "
                f"{height:.6f} "
                f"# conf={confidence:.4f}\n"
            )


# ============================================================
# PROCESS ONE SPLIT
# ============================================================

def process_split(
    model,
    image_dir,
    split_name
):

    print("\n")
    print("=" * 80)
    print(
        f"GENERATING {split_name.upper()} ANNOTATIONS"
    )
    print("=" * 80)

    print(
        f"Input directory:"
    )

    print(
        image_dir
    )

    # --------------------------------------------------------
    # Find images
    # --------------------------------------------------------

    images = get_images(
        image_dir
    )

    print(
        f"\nImages found: {len(images)}"
    )

    if len(images) == 0:

        print(
            "[ERROR] No images found."
        )

        return None

    # --------------------------------------------------------
    # Output directories
    # --------------------------------------------------------

    split_root = (
        OUTPUT_ROOT /
        split_name
    )

    labels_dir = (
        split_root /
        "labels"
    )

    visualization_dir = (
        split_root /
        "visualizations"
    )

    labels_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    visualization_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # COCO structure
    # --------------------------------------------------------

    coco = create_coco_structure()

    annotation_id = 1

    image_id = 1

    class_counter = Counter()

    images_with_detections = 0

    images_without_detections = 0

    total_detections = 0

    # ========================================================
    # Process images
    # ========================================================

    for image_path in tqdm(
        images,
        desc=f"YOLO {split_name}"
    ):

        try:

            # ------------------------------------------------
            # Read image size
            # ------------------------------------------------

            with Image.open(
                image_path
            ) as img:

                width, height = img.size

            # ------------------------------------------------
            # YOLO inference
            # ------------------------------------------------

            results = model.predict(

                source=str(image_path),

                imgsz=IMAGE_SIZE,

                conf=CONFIDENCE_THRESHOLD,

                iou=IOU_THRESHOLD,

                device=DEVICE,

                verbose=False

            )

            result = results[0]

            # ------------------------------------------------
            # COCO image entry
            # ------------------------------------------------

            coco["images"].append(

                {

                    "id":
                        image_id,

                    "file_name":
                        image_path.name,

                    "width":
                        width,

                    "height":
                        height

                }

            )

            detections = []

            # ------------------------------------------------
            # Extract predictions
            # ------------------------------------------------

            if result.boxes is not None:

                boxes = (
                    result.boxes.xyxy
                    .detach()
                    .cpu()
                    .numpy()
                )

                classes = (
                    result.boxes.cls
                    .detach()
                    .cpu()
                    .numpy()
                )

                scores = (
                    result.boxes.conf
                    .detach()
                    .cpu()
                    .numpy()
                )

                for box, cls, score in zip(
                    boxes,
                    classes,
                    scores
                ):

                    yolo_class = int(cls)

                    confidence = float(
                        score
                    )

                    # ------------------------------------------------
                    # Only person / car / bicycle
                    # ------------------------------------------------

                    if yolo_class not in YOLO_TO_SICDA:

                        continue

                    sicda_class = (
                        YOLO_TO_SICDA[
                            yolo_class
                        ]
                    )

                    # ------------------------------------------------
                    # Bounding box
                    # ------------------------------------------------

                    x1 = float(box[0])

                    y1 = float(box[1])

                    x2 = float(box[2])

                    y2 = float(box[3])

                    # ------------------------------------------------
                    # Clamp coordinates
                    # ------------------------------------------------

                    x1 = max(
                        0.0,
                        min(x1, width)
                    )

                    y1 = max(
                        0.0,
                        min(y1, height)
                    )

                    x2 = max(
                        0.0,
                        min(x2, width)
                    )

                    y2 = max(
                        0.0,
                        min(y2, height)
                    )

                    box_width = (
                        x2 - x1
                    )

                    box_height = (
                        y2 - y1
                    )

                    if box_width <= 1:
                        continue

                    if box_height <= 1:
                        continue

                    # ------------------------------------------------
                    # YOLO normalized format
                    # ------------------------------------------------

                    x_center = (
                        (x1 + x2) /
                        2.0 /
                        width
                    )

                    y_center = (
                        (y1 + y2) /
                        2.0 /
                        height
                    )

                    norm_width = (
                        box_width /
                        width
                    )

                    norm_height = (
                        box_height /
                        height
                    )

                    detections.append(

                        {

                            "class_id":
                                sicda_class,

                            "class_name":
                                SICDA_CLASS_NAMES[
                                    sicda_class
                                ],

                            "x1":
                                x1,

                            "y1":
                                y1,

                            "x2":
                                x2,

                            "y2":
                                y2,

                            "x_center":
                                x_center,

                            "y_center":
                                y_center,

                            "width":
                                norm_width,

                            "height":
                                norm_height,

                            "confidence":
                                confidence

                        }

                    )

                    # ------------------------------------------------
                    # Statistics
                    # ------------------------------------------------

                    class_counter[
                        SICDA_CLASS_NAMES[
                            sicda_class
                        ]
                    ] += 1

                    total_detections += 1

            # ------------------------------------------------
            # Save YOLO TXT
            # ------------------------------------------------

            txt_path = (
                labels_dir /
                f"{image_path.stem}.txt"
            )

            save_yolo_annotation(
                txt_path,
                detections
            )

            # ------------------------------------------------
            # COCO annotations
            # ------------------------------------------------

            for det in detections:

                coco_annotation = {

                    "id":
                        annotation_id,

                    "image_id":
                        image_id,

                    "category_id":
                        det["class_id"],

                    "bbox": [

                        det["x1"],

                        det["y1"],

                        det["x2"]
                        -
                        det["x1"],

                        det["y2"]
                        -
                        det["y1"]

                    ],

                    "area":
                        (
                            det["x2"]
                            -
                            det["x1"]
                        )
                        *
                        (
                            det["y2"]
                            -
                            det["y1"]
                        ),

                    "iscrowd":
                        0,

                    "score":
                        det["confidence"],

                    "pseudo_label":
                        True

                }

                coco[
                    "annotations"
                ].append(
                    coco_annotation
                )

                annotation_id += 1

            if detections:

                images_with_detections += 1

            else:

                images_without_detections += 1

            # ------------------------------------------------
            # Save visualization
            # ------------------------------------------------

            try:

                plotted = result.plot()

                visualization_path = (
                    visualization_dir /
                    image_path.name
                )

                # result.plot() returns BGR numpy array
                from PIL import Image as PILImage
                import numpy as np

                plotted_rgb = (
                    plotted[:, :, ::-1]
                )

                PILImage.fromarray(
                    np.asarray(
                        plotted_rgb
                    )
                ).save(
                    visualization_path
                )

            except Exception as vis_error:

                print(
                    f"\n[WARNING] Visualization failed:"
                    f" {image_path.name}"
                )

                print(
                    vis_error
                )

            image_id += 1

        except Exception as error:

            print(
                f"\n[ERROR] Failed:"
                f" {image_path}"
            )

            print(
                error
            )

    # ========================================================
    # Save COCO JSON
    # ========================================================

    json_path = (
        split_root /
        f"llvip_{split_name}_pseudo.json"
    )

    with open(
        json_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            coco,
            f,
            indent=2
        )

    # ========================================================
    # Save statistics
    # ========================================================

    stats = {

        "split":
            split_name,

        "total_images":
            len(images),

        "images_with_detections":
            images_with_detections,

        "images_without_detections":
            images_without_detections,

        "total_detections":
            total_detections,

        "class_distribution":
            dict(class_counter),

        "confidence_threshold":
            CONFIDENCE_THRESHOLD,

        "iou_threshold":
            IOU_THRESHOLD,

        "model":
            MODEL_NAME,

        "classes": {

            "1": "person",

            "2": "car",

            "3": "bike"

        }

    }

    stats_path = (
        split_root /
        "statistics.json"
    )

    with open(
        stats_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            stats,
            f,
            indent=2
        )

    # ========================================================
    # SUMMARY
    # ========================================================

    print("\n")
    print("-" * 80)
    print(
        f"{split_name.upper()} SUMMARY"
    )
    print("-" * 80)

    print(
        f"Images                 : "
        f"{len(images)}"
    )

    print(
        f"Images with detections : "
        f"{images_with_detections}"
    )

    print(
        f"Images without labels  : "
        f"{images_without_detections}"
    )

    print(
        f"Total detections       : "
        f"{total_detections}"
    )

    print(
        "\nClass distribution:"
    )

    print(
        f"  Person : "
        f"{class_counter['person']}"
    )

    print(
        f"  Car    : "
        f"{class_counter['car']}"
    )

    print(
        f"  Bike   : "
        f"{class_counter['bike']}"
    )

    print(
        "\nCOCO JSON:"
    )

    print(
        json_path
    )

    print(
        "\nYOLO labels:"
    )

    print(
        labels_dir
    )

    print(
        "\nVisualizations:"
    )

    print(
        visualization_dir
    )

    return {

        "json":
            json_path,

        "labels":
            labels_dir,

        "visualizations":
            visualization_dir,

        "stats":
            stats

    }


# ============================================================
# MAIN
# ============================================================

def main():

    print("\n")
    print("#" * 80)
    print(
        "# LLVIP AUTOMATIC PSEUDO-ANNOTATION GENERATOR"
    )
    print("#" * 80)

    print(
        "\nDataset:"
    )

    print(
        LLVIP_ROOT
    )

    print(
        "\nClasses:"
    )

    print(
        "1 = person"
    )

    print(
        "2 = car"
    )

    print(
        "3 = bike"
    )

    print(
        "\nModel:"
    )

    print(
        MODEL_NAME
    )

    print(
        "\nConfidence:"
    )

    print(
        CONFIDENCE_THRESHOLD
    )

    # ========================================================
    # Check directories
    # ========================================================

    print("\n")
    print("=" * 80)
    print(
        "CHECKING DATASET"
    )
    print("=" * 80)

    print(
        f"Train directory:"
    )

    print(
        f"  {TRAIN_IMAGE_DIR}"
    )

    print(
        f"Exists: {TRAIN_IMAGE_DIR.exists()}"
    )

    print(
        f"\nTest directory:"
    )

    print(
        f"  {TEST_IMAGE_DIR}"
    )

    print(
        f"Exists: {TEST_IMAGE_DIR.exists()}"
    )

    if not TRAIN_IMAGE_DIR.exists():

        raise FileNotFoundError(
            f"\nLLVIP train directory not found:\n"
            f"{TRAIN_IMAGE_DIR}"
        )

    # ========================================================
    # Load model
    # ========================================================

    print("\n")
    print("=" * 80)
    print(
        "LOADING YOLO MODEL"
    )
    print("=" * 80)

    print(
        f"Model: {MODEL_NAME}"
    )

    print(
        "\nFirst run may automatically download "
        "the pretrained model weights."
    )

    model = YOLO(
        MODEL_NAME
    )

    print(
        "\nYOLO model loaded successfully."
    )

    # ========================================================
    # Process TRAIN
    # ========================================================

    train_result = process_split(

        model=model,

        image_dir=TRAIN_IMAGE_DIR,

        split_name="train"

    )

    # ========================================================
    # Process TEST
    # ========================================================

    test_result = None

    if TEST_IMAGE_DIR.exists():

        test_result = process_split(

            model=model,

            image_dir=TEST_IMAGE_DIR,

            split_name="test"

        )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print("\n")
    print("#" * 80)
    print(
        "# ANNOTATION GENERATION COMPLETED"
    )
    print("#" * 80)

    print(
        "\nOutput root:"
    )

    print(
        OUTPUT_ROOT
    )

    print(
        "\nTRAIN:"
    )

    if train_result:

        print(
            f"  JSON:"
        )

        print(
            f"  {train_result['json']}"
        )

        print(
            f"\n  Labels:"
        )

        print(
            f"  {train_result['labels']}"
        )

        print(
            f"\n  Visualizations:"
        )

        print(
            f"  {train_result['visualizations']}"
        )

    print(
        "\nTEST:"
    )

    if test_result:

        print(
            f"  JSON:"
        )

        print(
            f"  {test_result['json']}"
        )

        print(
            f"\n  Labels:"
        )

        print(
            f"  {test_result['labels']}"
        )

        print(
            f"\n  Visualizations:"
        )

        print(
            f"  {test_result['visualizations']}"
        )

    print("\n")
    print("=" * 80)
    print(
        "IMPORTANT"
    )
    print("=" * 80)

    print(
        "These annotations are AUTOMATIC PSEUDO-LABELS."
    )

    print(
        "They should not be described as official "
        "LLVIP ground truth."
    )

    print(
        "\nRecommended next step:"
    )

    print(
        "Review several hundred visualization images "
        "before using these labels for training."
    )


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":

    main()